# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171102_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='description',
            new_name='detail',
        ),
    ]
