# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 11:37
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171103_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from=b'name', unique=False),
            preserve_default=True,
        ),
    ]
