# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20171103_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
